runtime: python39

# Environment variables
env_variables:
  ENVIRONMENT: "production"
  PROJECT_ID: "email-phishing-detector"

# Instance configuration
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Health checks
health_check:
  enable: true
  check_interval_sec: 10
  timeout_sec: 4
  healthy_threshold: 2
  unhealthy_threshold: 5
  restart_threshold: 60

# Static files (if you have frontend)
handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

# Skip certain files during deployment
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?tests/.*$
- ^(.*/)?test/.*$
- node_modules/
